name: Dynamic matrix example
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  agg_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: agg
        uses: ./agg
    outputs:
      ops: ${{steps.agg.outputs.ops}}

  matrix_1:
    needs: agg_1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        op: ${{fromJson(needs.agg_1.outputs.ops)}}
    outputs:
      out_1: ${{ steps.op.outputs.out_1 }}
      out_2: ${{ steps.op.outputs.out_2 }}
      out_3: ${{ steps.op.outputs.out_3 }}
# limitation: only includes one output from the matrix. workaround: predefined output
#      steps: ${{ toJson(steps) }}
    steps:
      - uses: actions/checkout@v2
#      - id: op
#        run: echo "::set-output name=out_${{ matrix.op.id }}::${{ matrix.op.id }}"
      - id: op
        uses: ./op
        with:
# limitation: cannot pass object to input. workaround: pass each value as input
#          op: ${{matrix.op}}
          id: ${{matrix.op.id}}

  agg_2:
    needs: [matrix_1]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{toJson(needs.matrix_1.outputs)}}"
      - uses: actions/checkout@v2
      - id: agg
        uses: ./agg
        with:
          out_1: ${{needs.matrix_1.outputs.out_1}}
          out_2: ${{needs.matrix_1.outputs.out_2}}
          out_3: ${{needs.matrix_1.outputs.out_3}}
